### ISSUE TITLE
again and again regression

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#387] opened 2019-08-31 16:15 UTC
Input:
```php
$var = $var + $var ?? '';
```

Input:
```php
function gen() {
  yield 0;
  yield from from();
  yield 4;
}
```

I honestly can’t understand what the problem is, why you can not devote a little more time to tests and details, what is the problem of being more responsible for the project or asking for help (hi, i am here and can test branches before merge :hand: )?

Each update is pain and regressions :disappointed: 

I understand that we all have work here and a little time, but what is the problem to wait for the review and feedback before merge?

**Comment by czosel** [comment] 2019-08-31 16:44
@evilebottnawi Just that I also understand the issue here: You're talking about pushing code directly to master which is breaking the CI build on master, right?
If so, then I'd also strongly encourage @ichiriac to always open a pull request for each change and only merge it when the CI passes. Also, it's always great if someone else who understands the codebase (e.g. @evilebottnawi) can look over it - that both helps to keep the quality up and also makes it easier for everyone else to keep track of the changes.

**Comment by evilebottnawi** [comment] 2019-08-31 16:45
@czosel yes, always wait green, do more tests and wait review, I am almost always available and respond very quickly

**Comment by evilebottnawi** [comment] 2019-08-31 17:00
Look regression here https://github.com/glayzzle/php-parser/commit/09c943cf143bf24762d17882dc5e94febba29e59, now parser works in php5 mode by default, before he works in php7 mode

**Comment by ichiriac** [comment] 2019-08-31 17:00
Hi @evilebottnawi - the problem is quite simple : 

> little time = quick & dirty = commits on master && skip tests.

The real problem here is that I don't use or need the parser, I'm maintaining it just for helping users like you, but as I'm not dirrectly using it so I can't spend time on it as I have real life projects to finish (even on my spare time)

A solution for yourself could be to fork the project, making changes as you need, publish releases under new NPM package (php-parser2 for example)

As you keep the fork link, I may merge some things, and maybe you can also merge fixes from it - you could then make decisions and organize the project as you want. Anyway, time will come when then project may become either abandoned or maintained by some one else (or maybe replaced by another solution)

Here the problem is quite simple, `this.php7` is undefined, and `this.php73` is true :
![Screenshot from 2019-08-31 18-32-51](https://user-images.githubusercontent.com/173203/64066778-5ba2ec80-cc1e-11e9-820d-bbae3e799fc0.png)

It's quite obvious to debug, you're missing the method to find where it breaks, and be aware, using a tool like `jison` forget to debug it as it does not run an algorithm so it's a pain to find the stack, lexer state etc ...

The regression is on https://github.com/glayzzle/php-parser/commit/09c943cf143bf24762d17882dc5e94febba29e59, and it was failling silently, not a matter of tests, (BTW you're welcome to contribute, the issue is here : https://github.com/glayzzle/php-parser/issues/49)

**Comment by ichiriac** [comment] 2019-08-31 17:01
lets close this issue, I've added husky, I will not be able to commit with breaking test

**Closed by ichiriac** 2019-08-31 17:01 UTC

**Comment by evilebottnawi** [comment] 2019-08-31 17:04
@ichiriac can you send a PR and wait review for me before merge? I will test branch and check code on something strange?

**Comment by ichiriac** [comment] 2019-08-31 17:27
@evilebottnawi don't put too much feelings, for me it's just an hobby, I don't expect anything from this project.

I've started to work alone, the `master` branch is the unstable/dev/testing even if it's an uggly & bad practice but it's good enough for me as I can push quick fixes without merging.

I think as you need to retain releases and handle yourself your changes, it's better to fork and try to keep it in sync if possible.

Also I think I'll wait some time before making the next release, so you'll have more room to make changes as you need.

Anyway, thanks for your contributions, I'll try to reply and help you as much I can.

**Comment by evilebottnawi** [comment] 2019-08-31 17:36
@ichiriac I had a discussion with WordPress developers and laravel, they wait php prettier, so it is the serious project for us, the guys also have money and maybe after stable release we will get funds, some of them we can to pay for your help in the work done, so I suggest that you take the project more seriously

**Comment by ichiriac** [comment] 2019-08-31 18:03
I don't do this for money @evilebottnawi, and @czosel as owner I make my own (maybe bad but assumed) decisions depending on what I assume

Please go ahead, fork the project and use a new npm alias - it's really not a problem for me, and I will still try to help you as before

**Comment by evilebottnawi** [comment] 2019-08-31 18:13
@ichiriac why you have `Sponsor` button in above? I just suggested that you take it more responsible to the project and offered you a simple and convenient work scheme to avoid problems in the future (branch -> green ci -> approve -> merge).

I don’t know why you closed the discussion here, because I can still talk, but apparently I better not do it. All I'm trying to do is make someone’s work better and more convenient. And I don’t understand why it’s bad to get money for your work, even if you did it for free before.

**Comment by ichiriac** [comment] 2019-08-31 19:56
You can talk as you are a collaborator with extra privileges - this conversation is off topic and does not concern issues on php-parser, you can still continue to talk with me but I would prefer to do it in private messages, for example on https://gitter.im/ichiriac
