### ISSUE TITLE
Curly braces in encapsed string, again

### ISSUE THREAD

**Issue by czosel** [glayzzle/php-parser#101] opened 2017-12-23 11:31 UTC
When working on prettier support for PHP (#100) i noticed something odd about curly braces in encapsed strings:
```php
"Hello {$foo}";
```
yields
```javascript
[ String {
            kind: 'string',
            loc: 
             Location {
               source: null,
               start: Position { line: 1, column: 1, offset: 1 },
               end: Position { line: 1, column: 7, offset: 7 } },
            value: 'Hello ',
            isDoubleQuote: false },
          Variable {
            kind: 'variable',
            loc: 
             Location {
               source: null,
               start: Position { line: 1, column: 8, offset: 8 },
               end: Position { line: 1, column: 12, offset: 12 } },
            name: 'foo',
            byref: false,
            curly: false } ],
```
But 
```php
"Hello ${foo}";
```
yields 
```javascript
[ String {
            kind: 'string',
            loc: 
             Location {
               source: null,
               start: Position { line: 1, column: 1, offset: 1 },
               end: Position { line: 1, column: 7, offset: 7 } },
            value: 'Hello ',
            isDoubleQuote: false },
          Variable {
            kind: 'variable',
            loc: 
             Location {
               source: null,
               start: Position { line: 1, column: 7, offset: 7 },
               end: Position { line: 1, column: 13, offset: 13 } },
            name: 'foo',
            byref: false,
            curly: true } ],
```
In the first case, the information about the surrounding curly braces seems to be lost, which makes it hard to re-print the node the way it was found. 
What do you think about this? If there is no semantic difference between the two different styles, we might get away with setting `curly:true` in both cases?

**Comment by czosel** [comment] 2017-12-24 12:51
Hi @ichiriac, thanks for looking into this! I've been reading up on this a little bit before opening this issue, and i didn't find any concrete differences between the two syntaxes - but also no clear statement that they are equivalent. Let's hope you'll find out more :smile:

**Comment by ichiriac** [comment] 2017-12-26 21:29
The two are not the same. The `${varname}` is used to only resolve a variable name from a constant text. The other one is used to inject an expression value. In your example the two are equivalent, but I can use the same node as it's not the same use set.

Here a concrete example :

```php
<?php
$name = 'John Doe';
echo "It's ${name}s computer...";
```
> Without the `${....}` syntax I would be unable to use my variable without a concatenation 

NOTE : be aware that's an expression evaluation and not a constant varname string - already explained here : https://github.com/glayzzle/php-parser/issues/59#issuecomment-274199764 - so another valid example :

```php
<?php
function getVarName() {
  return 'name';
}
$name = 'John Doe';
echo "It's ${getVarName()}s computer...";
```

And here another use case :
```php
<?php
$obj = json_decode('{foo:123}');
echo "Foo is {$obj->foo} !";
```
---

Not 100% sure that's every use case but the `${....}` evalute a dynamic variable name and concat it, the `{$...}` evalute directly the value from the expression and concat it - but the last one works only from a variable instance.

**Comment by czosel** [comment] 2017-12-26 21:36
Wow, while that seems crazy, i think i get your point. What conclusion would you draw from this? Do we need a new node type to cover the "outer curly" case (`{$...}`)?

**Comment by ichiriac** [comment] 2017-12-26 22:22
:smile: it's not enough clear either for me, I need a bit more time to think about. 

I also have to fix this https://github.com/glayzzle/php-parser/issues/105, I'll be back on this soon when I'll be sure to handle every case - any proposal is welcome if you have ideas

**Comment by ichiriac** [comment] 2017-12-27 09:59
Ok, I think I got it. Lets introduce some vocab :

- `${varname}` is an evaluated variable name
- `{$varname}` is an evaluated variable value

The encapsed node *SHOULD* be able to distinguish that the evaluation of a variable value is enclosed by a curly. Here the problem is that `echo "$foo";` is strictly the same as `echo "{$foo}";`.

The evaluated variable name *SHOULD* follow the expr evaluation logic, so the `name` value of the variable node should in that case be a node (with the const type for example).

In principle we have already everything - but this is a breaking change, so it will be released under 3.0.0

Here the todo list :
- [ ] use the `curly: true` property on variable node when `{$var}`
- [ ] use a node on `name` property when `${var}`

Here the pseudo algorithm to unparser an encapsed array :
```js
while(item on encapsedValues) {
  if (kind of item is a "string") -> append the string value
  else if (kind of item is a "variable") {
    if (item have the curly flag) -> append '{$' + item.name + '}'
    else if (item have a name node) -> append '${' + unparse(item.name) + '}'
    else -> append '$' + item.name 
  }
  else -> append '{' + unparse(item) + '}'
} 
```
---
@czosel in principle it should cover any case ?

**Comment by czosel** [comment] 2017-12-27 16:35
Yes, that sounds perfect! I don't see any case that would not be covered with this. :100:

**Comment by evilebottnawi** [comment] 2018-02-23 13:19
@ichiriac i don't known related or not, maybe need new issue:
`$this->{self::PRICE_ATTRIBUTE}` we do not have information about `{` and `}` in ast, maybe we need `staticlookup.curly` true or false

**Closed** 2018-03-27 18:52 UTC
Labels: AST, enhancement
