### ISSUE TITLE
implement `EmptyStatement` node

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#378] opened 2019-08-28 15:02 UTC
Input:
```php
$var = 'test';;
```

Should be easy, not high priority

**Comment by ichiriac** [comment] 2020-01-06 18:48
It's a duplicate of https://github.com/glayzzle/php-parser/issues/272 - you will get an expression with a noop node.

**Closed by ichiriac** 2020-01-06 18:48 UTC
Labels: AST, feature
