### ISSUE TITLE
Don't have curly for propertylookup in offset

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#128] opened 2018-03-06 09:20 UTC
Example:
```php
$this->{quantity};
```

Ref: https://github.com/prettier/plugin-php/issues/112

**Comment by czosel** [comment] 2018-03-06 20:21
This might be a duplicate of #101

**Comment by ichiriac** [comment] 2018-03-06 21:11
Not really, here the problem is about unclear AST. In fact it's not really a bug as the output can be resolved as following :

![image](https://user-images.githubusercontent.com/173203/37058427-c63b88da-218a-11e8-9a2e-0fb07b960ca2.png)

If the `name` is an identifier node, use `'{' + name.name + '}'` or else use directly `name`.

I find it a bit ugly,  so I'll use this version in order to introduce changes on AST and make it more intuitive, related on https://github.com/glayzzle/php-parser/issues/62

**Comment by czosel** [comment] 2018-03-06 21:29
Oh, of course - and it's not even about `encapsed`. I guess i should take a break :wink:

**Comment by czosel** [comment] 2018-03-09 09:17
@ichiriac the workaround in our prettier plugin is actually not too bad: https://github.com/prettier/plugin-php/pull/183

**Comment by ichiriac** [comment] 2019-01-03 01:00
Hi @evilebottnawi,

I'm sorry that my reply took so long, I'm almost free & back now. I'll work this saturday all the day, I still plan to release it on a stable version soon.

I wish you an happy new year plenty of joy and cool projects :smile:

**Comment by ichiriac** [comment] 2019-01-07 08:37
Hi @evilebottnawi,

Could you check remaining issues and add the flag high-pri on every issue you need to be fixed for the stable version ? Like this I'll know on what to focus.

**Comment by ichiriac** [comment] 2019-01-22 23:39
hi, it's implemented, take a look at the comment https://github.com/glayzzle/php-parser/issues/248#issuecomment-456596682 in order to see the implementation rules

**Closed by ichiriac** 2019-01-22 23:39 UTC
Labels: AST, enhancement, high-pri
